'use strict';
// Run with Playwright installed; uses isolated in-memory Sheets, never the live API.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const http = require('node:http');
const path = require('node:path');
const { createHarness, example } = require('./programs.test');
const root = path.resolve(__dirname, '..');
(async () => {
  const harness = createHarness();
  const server = http.createServer((req, res) => {
    const relative = new URL(req.url, 'http://localhost').pathname;
    if (relative === '/downloads/teacher-note-v1.0.zip') {
      res.setHeader('Content-Type', 'application/zip');
      res.end(Buffer.from('PK\x05\x06' + '\x00'.repeat(18), 'binary'));
      return;
    }
    const file = path.resolve(root, '.' + relative);
    if (!file.startsWith(root + path.sep) || !fs.existsSync(file) || !fs.statSync(file).isFile()) { res.writeHead(404).end(); return; }
    const types = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.svg': 'image/svg+xml', '.png': 'image/png' };
    res.setHeader('Content-Type', types[path.extname(file)] || 'application/octet-stream');
    res.end(fs.readFileSync(file));
  });
  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  let browser;
  try {
    browser = await chromium.launch({ channel: 'chrome', headless: true });
    const page = await browser.newPage({ viewport: { width: 1365, height: 1000 } });
    const errors = [];
    page.on('pageerror', (error) => errors.push(error.message));
    let failList = false;
    let failTracking = false;
    let listRequests = 0;
    await page.exposeFunction('testProgramApi', (action, params) => {
      if (action === 'programList') listRequests++;
      if (failList && action === 'programList') throw new Error('연결 실패 테스트');
      if (failTracking && action === 'programTrack') throw new Error('집계 연결 실패 테스트');
      const payload = harness.call(action, params, ['programList', 'programDetail', 'programTrack'].includes(action));
      if (!payload.ok) throw new Error(payload.message);
      return payload;
    });
    await page.route('**/qna-config.js*', (route) => route.fulfill({ contentType: 'text/javascript', body: 'window.DATA_API={request: (action, params={})=>window.testProgramApi(action,params), isConfigured:()=>true};' }));
    await page.route('https://example.com/screen.png', (route) => route.fulfill({ contentType: 'image/svg+xml', body: '<svg xmlns="http://www.w3.org/2000/svg" width="840" height="360"><rect width="840" height="360" rx="12" fill="#e5f1eb"/><text x="55" y="95" font-size="32" fill="#155747">Student Manager · Preview</text><rect x="55" y="145" width="730" height="150" rx="10" fill="white"/></svg>' }));
    const base = `http://127.0.0.1:${server.address().port}`;
    await page.goto(base + '/programs.html');
    await page.getByText('아직 등록된 프로그램이 없습니다.').waitFor();
    assert.deepEqual(await page.locator('#programCategory option').allTextContents(), ['전체', '업무', '수업', '기타']);
    await page.getByRole('button', { name: '관리자 글쓰기' }).click();
    for (const key of ['title', 'version', 'windows', 'summary', 'downloadUrl']) await page.locator(`#programForm [name="${key}"]`).fill(example[key]);
    assert.deepEqual(await page.locator('#programForm [name="category"] option').allTextContents(), ['업무', '수업', '기타']);
    await page.locator('#programForm [name="category"]').selectOption('업무');
    await page.locator('#programBody').fill('## 프로그램 소개\n학생 목록과 상담 기록을 정리합니다.');
    await page.locator('#programImageUrl').fill('https://example.com/screen.png');
    await page.locator('#programImageAlt').fill('학생 관리 화면');
    await page.getByRole('button', { name: '그림 삽입' }).click();
    await page.locator('#programPreview summary').click();
    await page.locator('#programPreviewBody img').waitFor();
    await page.locator('#programForm [name="adminPassword"]').fill('wrong');
    await page.getByRole('button', { name: '게시글 저장' }).click();
    await page.locator('#editorMessage').filter({ hasText: '관리자 비밀번호가 맞지 않습니다.' }).waitFor();
    assert.ok((await page.locator('#programBody').inputValue()).includes('![학생 관리 화면]'));
    await page.locator('#programForm [name="adminPassword"]').fill('admin-test');
    await page.getByRole('button', { name: '게시글 저장' }).click();
    await page.getByRole('link', { name: '프로그램 다운로드' }).waitFor();
    assert.equal(await page.getByRole('link', { name: '프로그램 다운로드' }).getAttribute('href'), example.downloadUrl);
    assert.equal(await page.locator('#programDetail img').count(), 1);
    await page.locator('#programCommentForm [name="name"]').fill('방문자');
    await page.locator('#programCommentForm [name="password"]').fill('my-secret');
    await page.locator('#programCommentForm [name="text"]').fill('사용하기 편리해요. <img src=x onerror=alert(1)>');
    await page.getByRole('button', { name: '댓글 저장' }).click();
    await page.locator('#programComments').getByText('사용하기 편리해요.', { exact: false }).waitFor();
    assert.equal(await page.locator('#programComments img').count(), 0);
    await page.locator('#programComments').getByRole('button', { name: '수정', exact: true }).click();
    await page.locator('#programCommentForm [name="password"]').fill('my-secret');
    await page.locator('#programCommentForm [name="text"]').fill('수정된 사용 후기입니다.');
    await page.getByRole('button', { name: '댓글 저장' }).click();
    await page.locator('#programComments').getByText('수정된 사용 후기입니다.').waitFor();
    await page.locator('#programCommentForm [name="asAdmin"]').check();
    await page.locator('#programCommentForm [name="password"]').fill('admin-test');
    await page.locator('#programCommentForm [name="text"]').fill('의견 감사합니다. 다음 버전에 반영하겠습니다.');
    await page.getByRole('button', { name: '댓글 저장' }).click();
    await page.locator('#programComments .program-badge').getByText('관리자').waitFor();
    await page.evaluate(() => scrollTo({ top: 0, behavior: 'instant' }));
    await page.screenshot({ path: '/tmp/mysh-programs-desktop.png', fullPage: true });
    const idHash = new URL(page.url()).hash;
    await page.getByRole('button', { name: '← 목록' }).click();
    await page.locator('.program-card').waitFor();
    await page.locator('#programSearch').fill('없는검색');
    await page.getByText('검색 결과가 없습니다.').waitFor();
    await page.locator('#programSearch').fill('');
    await page.locator('#programCategory').selectOption('수업');
    await page.getByText('검색 결과가 없습니다.').waitFor();
    await page.locator('#programCategory').selectOption('');
    await page.screenshot({ path: '/tmp/mysh-programs-list.png', fullPage: true });
    for (const width of [900, 820, 390]) {
      await page.setViewportSize({ width, height: 900 });
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `List overflow at ${width}`);
    }
    await page.getByRole('button', { name: '메뉴 열기' }).click();
    await page.locator('.site-nav').getByRole('link', { name: '프로그램 자료실' }).waitFor();
    await page.getByRole('button', { name: '메뉴 닫기' }).click();
    const beforeDirectOpen = listRequests;
    failList = true;
    await page.goto(base + '/programs.html' + idHash);
    await page.locator('#programDetail img').waitFor();
    assert.equal(listRequests, beforeDirectOpen, 'Direct article links must not wait for or request the full list');
    failList = false;
    await page.waitForFunction(() => document.querySelector('#programDetail [data-metric="viewCount"]')?.textContent === '1');
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Mobile detail overflow');
    await page.screenshot({ path: '/tmp/mysh-programs-mobile.png', fullPage: true });
    await page.locator('#programComments .program-comment').first().getByRole('button', { name: '삭제', exact: true }).click();
    await page.locator('#programDeleteForm [name="password"]').fill('wrong');
    await page.locator('#programDeleteForm').getByRole('button', { name: '삭제', exact: true }).click();
    await page.locator('#deleteMessage').filter({ hasText: '댓글 비밀번호가 맞지 않습니다.' }).waitFor();
    await page.locator('#programDeleteForm [name="password"]').fill('my-secret');
    await page.locator('#programDeleteForm').getByRole('button', { name: '삭제', exact: true }).click();
    await page.locator('#commentMessage').filter({ hasText: '댓글을 삭제했습니다.' }).waitFor();
    assert.equal(await page.locator('.program-comment').count(), 1);
    await page.getByRole('button', { name: '관리자 수정' }).click();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Mobile editor overflow');
    await page.screenshot({ path: '/tmp/mysh-programs-editor-mobile.png', fullPage: true });
    await page.locator('#programForm [name="version"]').fill('1.1.0');
    await page.locator('#programForm [name="downloadName"]').fill('교무수첩.zip');
    await page.getByRole('button', { name: '게시글 저장' }).click();
    // Admin password is still empty, so fill it before checking filename validation.
    await page.locator('#programForm [name="adminPassword"]').fill('admin-test');
    await page.getByRole('button', { name: '게시글 저장' }).click();
    await page.locator('#editorMessage').filter({ hasText: 'Releases 링크는 파일명 항목을 비워 두세요.' }).waitFor();
    await page.locator('#programForm [name="downloadUrl"]').fill('/downloads/teacher-note-v1.0.zip');
    await page.getByRole('button', { name: '게시글 저장' }).click();
    await page.getByText('버전 1.1.0 · Windows 10 / 11', { exact: true }).waitFor();
    const downloaded = page.waitForEvent('download');
    await page.getByRole('link', { name: '프로그램 다운로드' }).click();
    const download = await downloaded;
    assert.equal(download.suggestedFilename(), '교무수첩.zip');
    assert.equal(await download.failure(), null);
    await page.waitForFunction(() => document.querySelector('#programDetail [data-metric="downloadCount"]')?.textContent === '1');
    assert.equal(await page.locator('#programDetail [data-metric="viewCount"]').textContent(), '1', 'Editing and downloading do not add views');
    await page.getByRole('button', { name: '← 목록' }).click();
    assert.equal(await page.locator('.program-card [data-metric="downloadCount"]').textContent(), '1');
    await page.goto(base + '/programs.html' + idHash);
    await page.waitForFunction(() => document.querySelector('#programDetail [data-metric="viewCount"]')?.textContent === '2');
    // Verify persistence after a fresh page load, then continue the existing delete flow.
    await page.reload();
    await page.getByText('다운로드 파일: 교무수첩.zip', { exact: true }).waitFor();
    await page.waitForFunction(() => document.querySelector('#programDetail [data-metric="viewCount"]')?.textContent === '3');
    assert.equal(await page.locator('#programDetail [data-metric="downloadCount"]').textContent(), '1');
    failTracking = true;
    const offlineDownload = page.waitForEvent('download');
    await page.getByRole('link', { name: '프로그램 다운로드' }).click();
    assert.equal(await (await offlineDownload).failure(), null, 'Counter outage must not block downloading');
    await page.locator('#programStatsMessage').filter({ hasText: '횟수를 갱신하지 못했습니다.' }).waitFor();
    assert.equal(await page.locator('#programDetail [data-metric="downloadCount"]').textContent(), '1', 'Failed requests do not invent counts');
    failTracking = false;
    assert.equal(await page.getByRole('link', { name: '프로그램 다운로드' }).getAttribute('download'), '교무수첩.zip');
    await page.locator('#programDetail').getByRole('button', { name: '삭제', exact: true }).click();
    await page.locator('#programDeleteForm [name="password"]').fill('admin-test');
    await page.locator('#programDeleteForm').getByRole('button', { name: '삭제', exact: true }).click();
    await page.getByText('아직 등록된 프로그램이 없습니다.').waitFor();
    failList = true;
    await page.reload();
    await page.getByText('자료실 연결을 확인해 주세요.').waitFor();
    failList = false;
    await page.getByRole('button', { name: '다시 불러오기' }).click();
    await page.getByText('아직 등록된 프로그램이 없습니다.').waitFor();
    for (let i = 0; i < 10; i++) harness.call('programSave', { ...example, title: `테스트 프로그램 ${i}` });
    await page.reload();
    await page.getByText('프로그램 10개', { exact: true }).waitFor();
    assert.equal(await page.locator('.program-card').count(), 8);
    await page.getByRole('button', { name: '2페이지', exact: true }).click();
    assert.equal(await page.locator('.program-card').count(), 2);
    assert.deepEqual(errors, []);
    console.log('Program browser tests passed (desktop, mobile, images, CRUD, comments, retry).');
  } finally {
    if (browser) await browser.close();
    await new Promise((resolve) => server.close(resolve));
  }
})().catch((error) => { console.error(error); process.exitCode = 1; });
